name: CI

on:
  push:
    branches:
      - main
      - 'develop'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 由 GitHub 提供的身份验证令牌
          BRANCH: gh-pages # 指定要将页面部署到的分支
          FOLDER: . # 指定要部署的文件夹，比如 "public" 或者 "."